POST http://localhost:80/signin 
Content-Type:application/json

{
    "user":"Eliyahu4",
    "password":"E123456",
    "email":"Dffd4f@gmmd.com",
    "gender":true
}

###
POST http://127.0.0.1:80/login 
Content-Type:application/json

{
    "user":"eliran222",
    "password":"E123456"
}

###
GET http://localhost:80/getData
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWJhN2I4NGFkZTljZDdlYmU3ZWY0NiIsInVzZXIiOiJFbG5hdGFuMTEiLCJnZW5kZXIiOnRydWUsImlhdCI6MTY0NTk4NzUwNSwiZXhwIjoxNjQ4NTc5NTA1fQ.nnrq99RBO8vQf5Qoh6NslPPb4LAEpOTIpPOI8-_nnno

###
### testing post 
POST http://localhost:80/post 
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWY0ZDUxNzRjZjgxNjk0MGY4YTdiMiIsInVzZXIiOiJzaGlyYTM0MzIiLCJpYXQiOjE2NDYyMTg1OTQsImV4cCI6MTY0ODgxMDU5NH0._r-0bIbV3X7-KZUG2yTtpuC1BmmzzymT6qEevI95L5E
Content-Type:application/json

{
    "content":"אני אוהב שוקולד"
}

###

POST http://localhost:80/like 
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWJhN2I4NGFkZTljZDdlYmU3ZWY0NiIsInVzZXIiOiJFbG5hdGFuMTEiLCJnZW5kZXIiOnRydWUsImlhdCI6MTY0NTk4NzUwNSwiZXhwIjoxNjQ4NTc5NTA1fQ.nnrq99RBO8vQf5Qoh6NslPPb4LAEpOTIpPOI8-_nnno
Content-Type:application/json

{
    "postCommentID":"621cc1fa9b5d8d9144ad4721"
}

###
POST http://localhost:80/comment 
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWJhN2I4NGFkZTljZDdlYmU3ZWY0NiIsInVzZXIiOiJFbG5hdGFuMTEiLCJnZW5kZXIiOnRydWUsImlhdCI6MTY0NTk4NzUwNSwiZXhwIjoxNjQ4NTc5NTA1fQ.nnrq99RBO8vQf5Qoh6NslPPb4LAEpOTIpPOI8-_nnno
Content-Type:application/json

{
    "postID":"621f4ee074cf816940f8a804",
    "content":"יש לך פוסט יפהפה"
    
}


###

GET http://localhost:80/isUserAuth 
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWJhN2I4NGFkZTljZDdlYmU3ZWY0NiIsInVzZXIiOiJFbG5hdGFuMTEiLCJnZW5kZXIiOnRydWUsImlhdCI6MTY0NTk4NzUwNSwiZXhwIjoxNjQ4NTc5NTA1fQ.nnrq99RBO8vQf5Qoh6NslPPb4LAEpOTIpPOI8-_nnno
